version: "3.8"
services:
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ../values/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "4317:4317"   # grpc port otlp
      - "4318:4318"   # http port otlp
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      # - "9411"   # Zipkin receiver
    depends_on:
    #   - zipkin
      - prometheus
      - jaeger

  backend-parent:
    container_name: backend-parent
    build:
      context: ../backend-parent
    ports:
      - "5000:5000"
    depends_on:
      - otel-collector

  backend-child:
    container_name: backend-child
    build:
      context: ../backend-child
    ports:
      - "5001:5001"
    depends_on:
      - backend-parent

  script:
    container_name: script
    build:
      context: ../scripts/request
    depends_on:
      - backend-child

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "16686:16686"
      - "16685:16685"
      - "14269:14269"
      - "14250"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../values/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana grafana/grafana-enterprise
    ports:
      - "3000:3000"
    depends_on:
      - otel-collector

volumes:
  grafana-storage: