otelCollectorMetrics:
  config:
    exporters:
      clickhousemetricswrite:
        endpoint: tcp://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/?database=${CLICKHOUSE_DATABASE}&username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}
      clickhousemetricswrite/hostmetrics:
        endpoint: tcp://${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/?database=${CLICKHOUSE_DATABASE}&username=${CLICKHOUSE_USER}&password=${CLICKHOUSE_PASSWORD}
        resource_to_telemetry_conversion:
          enabled: true
      prometheus:
      endpoint: 0.0.0.0:8889
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: localhost:1777
      zpages:
        endpoint: localhost:55679
    processors:
      batch:
        send_batch_size: 10000
        timeout: 1s
      k8sattributes/hostmetrics:
        extract:
          metadata:
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.pod.start_time
          - k8s.deployment.name
          - k8s.node.name
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - from: resource_attribute
          name: k8s.pod.ip
        - from: resource_attribute
          name: k8s.pod.uid
        - from: connection
      memory_limiter: null
      resourcedetection:
        detectors:
        - env
        - system
        system:
          hostname_sources:
          - dns
          - os
        timeout: 2s
    receivers:
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu: {}
          disk: {}
          filesystem: {}
          load: {}
          memory: {}
          network: {}
      prometheus:
        config:
          scrape_configs:
          - job_name: otel-collector
            scrape_interval: 5s
            static_configs:
            - targets:
              - 0.0.0.0:8888
          - job_name: signoz-spanmetrics-collector
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_apm_signoz_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_apm_signoz_io_path
              target_label: __metrics_path__
            - action: replace
              separator: ':'
              source_labels:
              - __meta_kubernetes_pod_ip
              - __meta_kubernetes_pod_annotation_apm_signoz_io_port
              target_label: __address__
            - replacement: signoz-spanmetrics-collector
              target_label: job_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              target_label: signoz_k8s_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              target_label: signoz_k8s_instance
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: signoz_k8s_component
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: k8s_namespace_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: k8s_pod_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_uid
              target_label: k8s_pod_uid
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: k8s_container_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: k8s_node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_ready
              target_label: k8s_pod_ready
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_phase
              target_label: k8s_pod_phase
            scrape_interval: 60s
          - job_name: generic-collector
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_signoz_io_scrape
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_signoz_io_path
              target_label: __metrics_path__
            - action: replace
              separator: ':'
              source_labels:
              - __meta_kubernetes_pod_ip
              - __meta_kubernetes_pod_annotation_signoz_io_port
              target_label: __address__
            - replacement: generic-collector
              target_label: job_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              target_label: signoz_k8s_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
              target_label: signoz_k8s_instance
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: signoz_k8s_component
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: k8s_namespace_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: k8s_pod_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_uid
              target_label: k8s_pod_uid
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: k8s_container_name
            - action: drop
              regex: (.+)-init
              source_labels:
              - __meta_kubernetes_pod_container_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: k8s_node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_ready
              target_label: k8s_pod_ready
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_phase
              target_label: k8s_pod_phase
            scrape_interval: 60s
    service:
      extensions:
      - health_check
      - zpages
      - pprof
      pipelines:
        metrics:
          exporters:
          - clickhousemetricswrite
          - prometheus
          processors:
          - batch
          receivers:
          - prometheus
        metrics/hostmetrics:
          exporters:
          - clickhousemetricswrite/hostmetrics
          processors:
          - resourcedetection
          - k8sattributes/hostmetrics
          - batch
          receivers:
          - hostmetrics
      telemetry:
        metrics:
          address: 0.0.0.0:8888

